import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { api } from '@/lib/api'

const icons: Record<string, string> = { 'casual-shoes': '👟', 'oxford-shoes': '👞', 'loafer-shoes': '🥾', boots: '🥾', belts: '🪢' }

// ISR: Revalidate every 60 seconds
export const revalidate = 60

export default async function HomePage() {
  const [banner, categories, hotDeals] = await Promise.all([api.banner.get().catch(() => null), api.categories.list().catch(() => []), api.products.list({ hot_deal: true, in_stock: true, limit: 10 }).catch(() => [])])
  const topCategories = categories.slice(0, 4)
  const entries = await Promise.all(topCategories.map(async (category: any) => [category.id, await api.products.list({ category: category.slug, in_stock: true, limit: 6 }).catch(() => [])] as const))
  const categoryProducts = Object.fromEntries(entries)
  return <main className="min-h-screen bg-[#FAF5EF] pb-20"><Link href="/shop" className="sticky top-16 z-40 block bg-white px-4 py-3 shadow-sm"><div className="mx-auto flex max-w-md items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-sm text-gray-400">Search products...</div></Link>{banner?.mobile_image_url || banner?.desktop_image_url ? <>{banner.mobile_image_url && <Link href="/shop" className="mx-4 mt-4 block overflow-hidden rounded-2xl md:hidden"><img src={banner.mobile_image_url} alt="Banner" className="w-full object-cover"/></Link>}{banner.desktop_image_url && <Link href="/shop" className="mx-4 mt-4 hidden overflow-hidden rounded-2xl md:block"><img src={banner.desktop_image_url} alt="Banner" className="w-full object-cover"/></Link>}</> : <div className="mx-4 mt-4 flex min-h-36 items-center justify-between rounded-2xl bg-gradient-to-r from-[#AD3735] to-[#C4874A] p-6 text-white"><div><p className="text-sm text-white/80">Best Choice</p><h1 className="text-2xl font-bold">Premium Leather Goods</h1><Link href="/shop" className="mt-3 inline-block rounded-lg bg-white px-4 py-2 text-sm font-semibold text-[#AD3735]">Shop Now</Link></div><span className="text-6xl">🥾</span></div>}<section className="mt-6 px-4"><h2 className="mb-3 font-bold text-[#AD3735]">Categories</h2><div className="flex gap-3 overflow-x-auto pb-2">{categories.map((category: any) => <Link key={category.id} href={`/shop?category=${category.slug}`} className="flex w-24 shrink-0 flex-col items-center gap-2 rounded-xl bg-white p-3 shadow-sm">{category.image_url ? <img src={category.image_url} alt={category.name} className="h-12 w-12 rounded-lg object-cover"/> : <span className="text-3xl">{icons[category.slug] ?? '👟'}</span>}<span className="text-center text-xs text-gray-700">{category.name}</span></Link>)}</div></section><ProductRow title="🔥 Hot Deals" products={hotDeals} href="/shop"/>{topCategories.map((category: any) => <ProductRow key={category.id} title={category.name} products={categoryProducts[category.id] ?? []} href={`/shop?category=${category.slug}`}/>)}</main>
}
function ProductRow({ title, products, href }: { title: string; products: any[]; href: string }) { if (!products.length) return null; return <section className="mt-6 px-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-[#AD3735]">{title}</h2><Link href={href} className="flex items-center text-xs font-medium text-[#C4874A]">View More <ArrowRight className="ml-1 h-3 w-3"/></Link></div><div className="flex gap-3 overflow-x-auto pb-2">{products.map((product) => <Link key={product.id} href={`/shop/${product.id}`} className="w-40 shrink-0 overflow-hidden rounded-xl bg-white shadow-sm"><div className="h-36 bg-gray-100">{product.image_url ? <img src={product.image_url} alt={product.name} className="h-full w-full object-cover"/> : null}</div><div className="p-2"><p className="truncate text-sm font-semibold">{product.name}</p><p className="mt-1 font-bold text-[#AD3735]">৳{product.price}</p></div></Link>)}</div></section> }
